#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Aug 10 15:53:27 CEST 2019
# SW Build 2580384 on Sat Jun 29 08:04:45 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 499ddd400f774940b31cb9c384662dea --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_divisorUnit_behav xil_defaultlib.tb_divisorUnit xil_defaultlib.glbl -log elaborate.log"
xelab -wto 499ddd400f774940b31cb9c384662dea --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_divisorUnit_behav xil_defaultlib.tb_divisorUnit xil_defaultlib.glbl -log elaborate.log

