#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Aug 10 13:03:06 CEST 2019
# SW Build 2580384 on Sat Jun 29 08:04:45 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_divisorUnit_behav -key {Behavioral:sim_1:Functional:tb_divisorUnit} -tclbatch tb_divisorUnit.tcl -log simulate.log"
xsim tb_divisorUnit_behav -key {Behavioral:sim_1:Functional:tb_divisorUnit} -tclbatch tb_divisorUnit.tcl -log simulate.log

