webtalk_init -webtalk_dir /home/clmcasino/Desktop/Mult-Div-Unit/Multiply-Division-Unit/tbs/divisorUnit/vivadoProject/divisorUnit.sim/sim_1/behav/xsim/xsim.dir/tb_divisorUnit_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Aug 10 15:56:05 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2580384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6d1cc337-adb3-49fc-be94-0ade0cc5b9db" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "499ddd400f774940b31cb9c384662dea" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2219.740 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1900 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126168_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1488635701 -regid "" -xml /home/clmcasino/Desktop/Mult-Div-Unit/Multiply-Division-Unit/tbs/divisorUnit/vivadoProject/divisorUnit.sim/sim_1/behav/xsim/xsim.dir/tb_divisorUnit_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/clmcasino/Desktop/Mult-Div-Unit/Multiply-Division-Unit/tbs/divisorUnit/vivadoProject/divisorUnit.sim/sim_1/behav/xsim/xsim.dir/tb_divisorUnit_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/clmcasino/Desktop/Mult-Div-Unit/Multiply-Division-Unit/tbs/divisorUnit/vivadoProject/divisorUnit.sim/sim_1/behav/xsim/xsim.dir/tb_divisorUnit_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
